server {
    listen 80;
    server_name preview-landing.kenzoagent.com;

    root /var/www/preview-landing.kenzoagent.com;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
